### ISSUE TITLE
Code for scene completion

### ISSUE THREAD

**Issue by czvvd** [wangyida/disp3d#2]
Thanks for your work! Will you release code for training in scene completion datasets like NYU and CompleteScanNet?

**Comment by wangyida** [comment]
Hi thanks for your interested, the codes for completing NYU and CompleteScanNet are provided. `--dataset nyu` and `--dataset fusion` shall be used during training accordingly. The same for validation

**Comment by czvvd** [comment]
Thanks for reply. I see the&nbsp;--dataset fusion but the code does not contains nyu. I'm very interested in how to train on the NYU dataset. The idea of completing both object and scene is awesome.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangyida/disp3d"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月10日(星期五) 下午3:25
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [wangyida/disp3d] Code for scene completion (Issue #2)





 
Hi thanks for your interested, the codes for completing NYU and CompleteScanNet are provided. --dataset nyu and --dataset fusion shall be used during training accordingly. The same for validation
