### ISSUE TITLE
Code is under construction?

### ISSUE THREAD

**Issue by czvvd** [wangyida/disp3d#3]
Thanks for your work. I notice that there exists only one network architecture in the code but two on the paper. And I can't find the dataset download link (e.g. ShapeNet contains images). Also, will you release code for training scene completion task?

**Comment by wangyida** [comment]
First, the transformer model can be adjusted by replacing the MLP and graph pooling in PoinTr model with our downsampling operators during experiments training with option `--methods pointr`.
Secondly, the training with images is not reported in our paper, but it is possible if you download the images manually from the official ShapeNet dataset and PCN/MSN/MVP 3D completion supervision
